### PR TITLE
[WIP] Add custom filter to solve duplicate key issue (issue 42)

### PR DESCRIPTION
**Pull request by ic4f**
See issue 42 for problem description + comments in seqtodict.py
Simplest way to run the unit tests:  `python -m unittest discover` from root dir.

### CODE REVIEW

**Comment by ic4f** [comment]
Sorry for the failing tests in prev.commits - I hadn't setup travis for those, so I missed them (that's what happens when committing at 3am...) All fixed now. 
@natefoo : please take a look: this should address a minor problem resulting from commit b69cc10 (Jun 22), lines 201-202).

**Comment by ic4f** [comment]
So, apparently, uwsgi_yaml takes care of this already. The 2 filters are different: uwsgi_yaml takes in a dictionary and "flattens" ALL sequences, whereas seqtodict takes in a formatted yaml string and 'flattens" only those sequences that have a given KEY. Still, given that we have uwsgi_yaml, seqtodict is not needed at this time,  so I'm closing this PR.

There's still an error in the sample code (see advanced playbook: duplicate keys/mule). I'll submit a separate PR for that.

**Comment by eslerm** [comment]
> There's still an error in the sample code (see advanced playbook: duplicate keys/mule). I'll submit a separate PR for that.

Each mule creates a mule worker in uWSGI syntax https://uwsgi-docs.readthedocs.io/en/latest/Mules.html

**Comment by ic4f** [comment]
> > There's still an error in the sample code (see advanced playbook: duplicate keys/mule). I'll submit a separate PR for that.
> 
> Each mule creates a mule worker in uWSGI syntax https://uwsgi-docs.readthedocs.io/en/latest/Mules.html
Yes, which make it a valid config for uwsgi. However, Ansible expects legal YAML, which does not allow duplicate dictionary keys. As a result, Ansible with process *only the last key*. (you can see that message when you run that playbook - and I hope I'm not missing anything here..)

**Comment by eslerm** [comment]
That sounds right.

There is a variable for using real yaml if you have a libyaml compiled version of uWSGI. That doesn't fix the readme though :)

**Comment by ic4f** [comment]
> That sounds right.
> 
> There is a variable for using real yaml if you have a libyaml compiled version of uWSGI. That doesn't fix the readme though :)

Yes, it's the ```galaxy_uwsgi_yaml_parser``` option. However, the playbook itself is processed by ansible (which uses libyaml), so it has to be valid yaml. So the parser option sets the format for the *output*  configuration for uwsgi, but has no effect on how the input playbook code is parsed by ansible.
And thanks for looking at this - I'm not at all sure I'm not missing stuff, so an extra pair of eyes is very helpful!

**Pull request closed without merging**
