### PR TITLE
Fix pip at 8.0.0

### PR DESCRIPTION
**Pull request by mvdbeek**
Since pip seems to be evolving rapidly as of recent. 
Otherwise we're getting the [import errors](https://travis-ci.org/ARTbio/ansible-artimed/builds/104456943#L1663) on new instances.

### CODE REVIEW

**Comment by mvdbeek** [comment]
@natefoo maybe you have a better idea?

**Comment by natefoo** [comment]
`--no-index --find-links https://wheels.galaxyproject.org/simple/pip` should prevent it from installing a newer pip from PyPI (unless that newer version is already installed). This was discussed on IRC today since that's exactly what the case will always be with Travis. The proposed solution is an "always install Galaxy pip even if it's a 'downgrade'" option, although I think we should probably make this the default as long as `--no-replace-pip` is not specified.

That said, I am not sure if it's possible with pip if you don't specify the exact version as part of `pip install` as you've done here, which I would prefer not to do because I want to be able to release bug fixes.

**Comment by mvdbeek** [comment]
@natefoo yep, this was a workaround for travis ... I was first experimenting with downgrading the installed pip to 7.1.2 prior to running tests, but that didn't work. Perhaps the ansible pip module doesn't respect `--no-index` ?

**Comment by natefoo** [comment]
Hrm, frustrating, and Ansible hides away the real failure. I believe that version should be `8.0.0+gx1`, but hold on a bit, I'm going to make a new `8.0.2+gx1` pip shortly.

**Comment by mvdbeek** [comment]
Specifying `8.0.0` seems to always catch `8.0.0+gx1`, so at least this wouldn't prevent a potential `8.0.0+gx2` to get installed ...

**Comment by natefoo** [comment]
Ah ok, interesting

**Comment by natefoo** [comment]
@mvdbeek Can you update it to `8.0.2`? I think we're good to go then. You can also drop `--pre` from the pip args.

**Comment by mvdbeek** [comment]
@natefoo done, thanks for looking into this!

**Comment by natefoo** [comment]
Thank you for fixing it!

**Comment by natefoo** [comment]
Just for the record, this won't be in galaxy.ansible.com until ansible/galaxy-issues#108 is resolved.

**Pull request merged**
