### PR TITLE
Allow changing mode of static files

### PR DESCRIPTION
**Pull request by hexylena**
for e.g. welcome.html to be readable by nginx

### CODE REVIEW

**Comment by hexylena** [comment]
```
148 ubuntu@gat-8:~/git-gat$ ls -al files/galaxy/themes.yml 
-rw-rw-r-- 1 ubuntu ubuntu 1654 Apr 14 11:55 files/galaxy/themes.yml
ubuntu@gat-8:~/git-gat$ ls -al /srv/galaxy/config/themes.yml
-r----xrw- 1 root galaxy 1654 Apr 14 11:56 /srv/galaxy/config/themes.yml
```

yeah that's relevant. And wow what bizarre permissions. 

I'm guessing because internally we have an octal number (which yaml parses as a number) for `galaxy_config_perms`, 

```
>>> yaml.load("test: 0640")
{'test': 416}
```

yeah that's that nonsense for sure.

**Comment by hexylena** [comment]
This is...probably better.

**Comment by kysrpex** [comment]
Thanks for fixing this, I was using a post task up to now.

**Comment by hexylena** [comment]
@kysrpex which files were you using it for? (i.e. is there something in the training that should have more readable permissions?)

**Comment by natefoo** [comment]
How is it not parsing the defaults as octal? I'm never clear on when it does and doesn't. But seems like we should just quote both of them to be explicit that they are not octal?

**Review by natefoo — APPROVED** [review]

**Comment by hexylena** [comment]
> How is it not parsing the defaults as octal?

It does, directly into an int (416). So if that gets turned into a string (as happens via `"{{ ... }}"`) then it gets mis-interpreted. As far as I can tell there's no way to tell ansible "hey this is actually an int even though you wanted it quoted because it's a templated var".

Which means it's probably... impossible?

> I'm never clear on when it does and doesn't. But seems like we should just quote both of them to be explicit that they are not octal?

`0NNN` (parse by yaml), `"0NNN"` (parsed by ansible) both get turned into octals, `"NNN"` also for some reason gets interpreted as octal, rather than anything else. from the docs:

> For those used to /usr/bin/chmod remember that modes are actually octal numbers. You must either add a leading zero so that Ansible's YAML parser knows it is an octal number (like 0644 or 01777)or quote it (like '644' or '1777') so Ansible receives a string and can do its own conversion from string into number. Giving Ansible a number without following one of these rules will end up with a decimal number which will have unexpected results.

**Pull request merged**
