### PR TITLE
Ensure tool_dependency_dir exists

### PR DESCRIPTION
**Pull request by mvdbeek**
This should make it easier to get started and I think this goes in the same direction as https://github.com/galaxyproject/galaxy/pull/2480.
Another place for this would be ansible-galaxy-tools, but I feel it makes most sense here.

### CODE REVIEW

**Comment by mvdbeek** [comment]
anyone? @bgruening @jmchilton ?

**Comment by mvdbeek** [comment]
thanks @jmchilton !

**Comment by jmchilton** [comment]
Sorry for the delay @mvdbeek - I sort of think of this as Nate territory and didn't want to stomp on it - but I think he is hard at work making Galaxy packages.

**Comment by mvdbeek** [comment]
No problem, I was under that impression too!

**Pull request merged**
