### PR TITLE
Support for running Galaxy from systemd using Gravity (galaxyctl)

### LINKED ISSUE #137: `__galaxy_user_group` is undefined if `galaxy_manage_paths` is not enabled
However, the systemd service unit template assumes that it is. We should move the tasks that collect and set those variables to an always-run task include file between the `galaxy_create_user` and `galaxy_manage_paths` tasks.

### PR DESCRIPTION
**Pull request by natefoo**
Also, support systemd user scope (`systemctl --user ...`).

Also fixed #137.

### CODE REVIEW

**Comment by natefoo** [comment]
Draft until I update the README.

**Comment by natefoo** [comment]
`galaxy_systemd_mode` should probably default to gravity if the version is >= 22.05?

**Comment by natefoo** [comment]
> `galaxy_systemd_mode` should probably default to gravity if the version is >= 22.05?

This unfortunately creates a circular dependency - you don't know what the version is until after the clone task, but the clone task notifies the restart handler, the name of which would be templated conditionally based on the version. I haven't been able to come up with a solution.

**Comment by guerler** [comment]
Is it possible to set a flag upfront (for now) to distinguish the two?

**Comment by natefoo** [comment]
Yes, you can currently set it manually, but it will have to be mule (uwsgi) for backwards compatibility unfortunately. Which will completely break under 22.05.

**Comment by natefoo** [comment]
Ok I think I got the automatic `galaxy_systemd_mode` working.

**Comment by mvdbeek** [comment]
There's a merge conflict now

**Comment by natefoo** [comment]
`path_join` isn't critical, but Ansible 2.9 is end of life as of December 2021, so perhaps we should just update the minimum version to 2.10 rather than make this backwards compatible?

**Comment by natefoo** [comment]
I think the restart shortly after starting is the issue here, but I've been unable to come up with a way to avoid it so far.

**Comment by mvdbeek** [comment]
Can you dump the beat logs ?

**Comment by mvdbeek** [comment]
@guerler and I had a look at this, the celery-beat seemingly fails because of permission issues:
```
__    -    ... __   -        _
LocalTime -> 2022-05-04 16:36:21
Configuration ->
    . broker -> sqlalchemy+sqlite:////srv/galaxy/var/universe.sqlite
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> celerybeat-schedule
    . logfile -> [stderr]@%DEBUG
    . maxinterval -> 5.00 minutes (300s)
No Galaxy config file found, running from current working directory: /srv/galaxy/server
[2022-05-04 16:36:27,286: DEBUG/MainProcess] Setting default socket timeout to 30
[2022-05-04 16:36:27,286: INFO/MainProcess] beat: Starting...
[2022-05-04 16:36:27,288: ERROR/MainProcess] Removing corrupted schedule file 'celerybeat-schedule': error(13, 'Permission denied')
Traceback (most recent call last):
  File "/srv/galaxy/venv/lib/python3.8/site-packages/celery/beat.py", line 533, in setup_schedule
    self._store = self._open_schedule()
  File "/srv/galaxy/venv/lib/python3.8/site-packages/celery/beat.py", line 523, in _open_schedule
    return self.persistence.open(self.schedule_filename, writeback=True)
  File "/usr/lib/python3.8/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.8/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.8/dbm/__init__.py", line 95, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 13] Permission denied: 'celerybeat-schedule'
[2022-05-04 16:36:27,289: CRITICAL/MainProcess] beat raised exception <class '_gdbm.error'>: error(13, 'Permission denied')
Traceback (most recent call last):
  File "/srv/galaxy/venv/lib/python3.8/site-packages/celery/beat.py", line 533, in setup_schedule
    self._store = self._open_schedule()
  File "/srv/galaxy/venv/lib/python3.8/site-packages/celery/beat.py", line 523, in _open_schedule
    return self.persistence.open(self.schedule_filename, writeback=True)
  File "/usr/lib/python3.8/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.8/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.8/dbm/__init__.py", line 95, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 13] Permission denied: 'celerybeat-schedule'
```
I think the schedule file is going to be created in `${{galaxy_root}}`, and that fails with the privsep setup.

**Comment by mvdbeek** [comment]
Looks like the test timed out while Galaxy was still auto-installing Conda. Should we just disable that for the test ?

**Comment by guerler** [comment]
@natefoo is it possible to increase the timeout here?

**Comment by mvdbeek** [comment]
it's the Conda auto install, we should just turn that off

**Pull request merged**
